# Generated by Django 2.1.5 on 2019-01-15 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_one', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('street_two', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('street_three', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=20)),
                ('zip', models.CharField(blank=True, default='', max_length=5)),
                ('city', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=20)),
                ('area', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete='SET_NULL', related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
