# Generated by Django 2.1.5 on 2019-01-31 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('rbac', '0003_auto_20190117_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Organization'),
        ),
    ]
