# Generated by Django 2.1.5 on 2019-01-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20190131_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code_name',
            field=models.CharField(default='', max_length=50, null=''),
        ),
    ]
